torchvision is not available - cannot save figures
speechbrain.core - Beginning experiment!
speechbrain.core - Experiment folder: results/train_whisper/2024
librispeech_prepare - Data_preparation...
The current working directory running check_librispeech_folders is: /users/acp23jlc/miniproject/speechbrain/TEAM2_modifications
librispeech_prepare - Creating csv lists in  results/train_whisper/2024/train-clean-100.csv...
  0%|          | 0/28539 [00:00<?, ?it/s] 14%|█▍        | 3963/28539 [01:20<08:17, 49.40it/s] 14%|█▍        | 3963/28539 [01:40<08:17, 49.40it/s] 43%|████▎     | 12155/28539 [02:39<03:34, 76.31it/s] 71%|███████▏  | 20347/28539 [02:40<01:03, 128.39it/s]100%|██████████| 28539/28539 [02:40<00:00, 181.71it/s]100%|██████████| 28539/28539 [02:41<00:00, 177.00it/s]
librispeech_prepare - results/train_whisper/2024/train-clean-100.csv successfully created!
librispeech_prepare - Creating csv lists in  results/train_whisper/2024/dev-clean.csv...
  0%|          | 0/2703 [00:00<?, ?it/s]100%|██████████| 2703/2703 [00:26<00:00, 102.65it/s]100%|██████████| 2703/2703 [00:26<00:00, 101.78it/s]
librispeech_prepare - results/train_whisper/2024/dev-clean.csv successfully created!
librispeech_prepare - Creating csv lists in  results/train_whisper/2024/test-clean.csv...
  0%|          | 0/2620 [00:00<?, ?it/s]100%|██████████| 2620/2620 [00:27<00:00, 94.07it/s]100%|██████████| 2620/2620 [00:28<00:00, 93.31it/s]
librispeech_prepare - results/train_whisper/2024/test-clean.csv successfully created!
speechbrain.dataio.dataio - results/train_whisper/2024/train.csv is created.
speechbrain.core - Exception:
Traceback (most recent call last):
  File "/users/acp23jlc/miniproject/speechbrain/TEAM2_modifications/../recipes/LibriSpeech/ASR/transformer/TEAM2_train_with_whisper.py", line 293, in <module>
    train_data, valid_data, test_datasets = dataio_prepare(hparams, tokenizer)
  File "/users/acp23jlc/miniproject/speechbrain/TEAM2_modifications/../recipes/LibriSpeech/ASR/transformer/TEAM2_train_with_whisper.py", line 193, in dataio_prepare
    test_datasets[name] = sb.dataio.dataset.DynamicItemDataset.from_csv(
  File "/users/acp23jlc/miniproject/speechbrain/speechbrain/dataio/dataset.py", line 408, in from_csv
    data = load_data_csv(csv_path, replacements)
  File "/users/acp23jlc/miniproject/speechbrain/speechbrain/dataio/dataio.py", line 129, in load_data_csv
    with open(csv_path, newline="") as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/train_whisper/2024/test-other.csv'
